name: fit_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  permission_handler: ^11.3.0
  intl: ^0.19.0
  sensors_plus: ^5.0.1
  health: ^10.2.0
  syncfusion_flutter_charts: ^25.1.42+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
