name: fit_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.0
  intl: ^0.19.0
  sensors_plus: ^4.0.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
